version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule: {interval: weekly}
    groups:
      anchore:
        patterns: ['github.com/anchore/*']
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}
